version: "3.2"
networks:
  back-tier:
services:
  db:
    image: mariadb:10.11
    restart: unless-stopped
    networks:
      - back-tier
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MARIADB_AUTO_UPGRADE: 1
    user: ${USER_ID}:${GROUP_ID}
    volumes:
      - ./docker/data/db:/var/lib/mysql
  fpm:
    build:
      context: docker/fpm
      args:
        USER_ID: ${USER_ID}
        GROUP_ID: ${GROUP_ID}
      target: ${APP_ENV}
    networks:
      - back-tier
    restart: unless-stopped
    environment:
      APP_ENV: ${APP_ENV}
      DATABASE_URL: "mysql://${DB_USER}:${DB_PASSWORD}@${DB_HOST}:3306/${DB_NAME}?serverVersion=${DB_IMAGE_VERSION}-MariaDB"
    volumes:
      - .:/var/www/repro
      - /etc/localtime:/etc/localtime:ro
  web:
    build:
      context: docker/web
      args:
        USER_ID: ${USER_ID}
        GROUP_ID: ${GROUP_ID}
      target: ${APP_ENV}
    networks:
      - back-tier
    restart: unless-stopped
    links:
      - fpm
    volumes:
      - ./symfony/public:/var/www/repro/symfony/public
